Repository kth-cdate-courses/DD2480-CI, pull requests merged in 2023-02, with the labels that each got.

#17 Update .gitignore and stop tracking .vscode in git
  .gitignore
  .vscode/settings.json
Labels: bug, improvement

#22 Add maven wrapper
  ci-server/.mvn/wrapper/maven-wrapper.jar
  ci-server/.mvn/wrapper/maven-wrapper.properties
  ci-server/mvnw
  ci-server/mvnw.cmd
Labels: improvement, ci

#11 Implement commit fetching from file and api
  data.json
  status-site/package.json
  status-site/pnpm-lock.yaml
  status-site/src/logic/fetch_commit.ts
  status-site/src/logic/github.commit.types.ts
  status-site/src/pages/index.astro
Labels: feature, site

#12 Single commit page
  data.json
  status-site/src/logic/fetch_commit.ts
  status-site/src/logic/github.commit.types.ts
  status-site/src/pages/[commit].astro
  status-site/src/pages/index.astro
Labels: feature, site

#24 Add design for commit page
  status-site/src/components/CommitCard.astro
  status-site/src/layouts/Layout.astro
  status-site/src/logic/fetch_commit.ts
  status-site/src/pages/[commit].astro
Labels: feature, site

#31 feat: issue #30 add parsing of test/compile output
  ci-server/src/main/java/com/group1/FileParsingFailedException.java
  ci-server/src/main/java/com/group1/Output_parser.java
  ci-server/src/main/java/com/group1/Status.java
  ci-server/src/test/java/com/group1/Output_parserTest.java
  ci-server/testing_resources/compileFail.txt
  ci-server/testing_resources/testFail.txt
  ci-server/testing_resources/testSuccess.txt
Labels: feature, ci

#38 Pauline/feat/27 download code
  ci-server/pom.xml
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/DownloadFailedException.java
  ci-server/src/main/java/com/group1/RequestExtraction.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
  ci-server/src/test/java/com/group1/RequestExtractionTest.java
Labels: feature, ci

#40 Add method that inserts results from running the test into data.json
  ci-server/pom.xml
  ci-server/src/main/java/com/group1/Commit.java
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
  ci-server/testing_resources/.gitignore
  ci-server/testing_resources/json_unit_testing/README.md
Labels: feature, ci

#43 docs: issue #10 add README for ci-sever
  ci-server/README.md
Labels: documentation, ci

#44 docs: issue #41 add statement of contributions to readme
  README.md
Labels: documentation

#46 docs: assessment of our Team #35
  README.md
Labels: documentation

#61 Make ci-website fetch assessment branch
  status-site/src/logic/fetch_commit.ts
Labels: improvement, site

#58 fix: issue #57 change order of if statements
  ci-server/src/main/java/com/group1/Output_parser.java
  ci-server/src/test/java/com/group1/Output_parserTest.java
Labels: bug, ci

#66 Fix bug with parsing http request object
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/RequestExtraction.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
  ci-server/src/test/java/com/group1/RequestExtractionTest.java
Labels: bug, ci

#67 Fix issue 53 relative pathing errors
  .gitignore
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/RequestExtraction.java
Labels: bug, ci

#68 fix malformed url error, issue 47
  .gitignore
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/RequestExtraction.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
Labels: bug, ci

#69 Issue 54, fix method for setting status on GitHub
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
Labels: bug, ci

#70 Fix checkout to correct branch
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/RequestExtraction.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
Labels: bug, ci

#71 Fix deployment of front end
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/Status.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
  deploy.sh
Labels: bug, ci, site

#75 fix: #73 add prints showing state of server
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
Labels: improvement

#79 Ignore error file for deployment script
  .gitignore
Labels: improvement, ci

#87 docs: issue #55 fix folder structure in README
  ci-server/README.md
Labels: documentation, ci

#82 fix: Fix #42, add setup steps to README file
  README.md
Labels: improvement, ci

#86 docs: add comments #78
  ci-server/src/main/java/com/group1/Commit.java
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
  ci-server/src/main/java/com/group1/Output_parser.java
  ci-server/src/main/java/com/group1/RequestExtraction.java
  ci-server/src/main/java/com/group1/Status.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
  ci-server/src/test/java/com/group1/Output_parserTest.java
  ci-server/src/test/java/com/group1/RequestExtractionTest.java
Labels: documentation, ci

#92 docs: issue #89 fix javadocs for output_parser
  ci-server/src/main/java/com/group1/Output_parser.java
Labels: documentation, ci

#94 Add acknowledgement
  README.md
Labels: improvement, ci

#93 fix: issue #88 fix memory leak in output_parser
  ci-server/src/main/java/com/group1/Output_parser.java
Labels: bug, ci

#95 Make sure the deployment script is found
  ci-server/src/main/java/com/group1/ContinuousIntegrationServer.java
Labels: improvement, ci

#96 issue #48 generate javadoc
  README.md
  ci-server/src/main/java/com/group1/Output_parser.java
  ci-server/src/test/java/com/group1/ContinuousIntegrationServerTest.java
  javadoc/allclasses-index.html
  javadoc/allpackages-index.html
  javadoc/com/group1/Commit.html
  javadoc/com/group1/ContinuousIntegrationServer.html
  javadoc/com/group1/ContinuousIntegrationServerTest.html
  javadoc/com/group1/DownloadFailedException.html
  javadoc/com/group1/FileParsingFailedException.html
  javadoc/com/group1/Output_parser.html
  javadoc/com/group1/Output_parserTest.html
  javadoc/com/group1/RequestExtraction.html
  javadoc/com/group1/RequestExtractionTest.html
  javadoc/com/group1/Status.html
  javadoc/com/group1/package-summary.html
  javadoc/com/group1/package-tree.html
  javadoc/element-list
  javadoc/help-doc.html
  javadoc/index-files/index-1.html
  javadoc/index-files/index-10.html
  javadoc/index-files/index-11.html
  javadoc/index-files/index-12.html
  javadoc/index-files/index-13.html
  javadoc/index-files/index-14.html
  javadoc/index-files/index-15.html
  javadoc/index-files/index-2.html
  javadoc/index-files/index-3.html
  javadoc/index-files/index-4.html
  javadoc/index-files/index-5.html
  javadoc/index-files/index-6.html
  javadoc/index-files/index-7.html
  javadoc/index-files/index-8.html
  javadoc/index-files/index-9.html
  javadoc/index.html
  javadoc/jquery-ui.overrides.css
  javadoc/legal/COPYRIGHT
  javadoc/legal/LICENSE
  javadoc/legal/jquery.md
  javadoc/legal/jqueryUI.md
  javadoc/member-search-index.js
  javadoc/module-search-index.js
  javadoc/overview-tree.html
  javadoc/package-search-index.js
  javadoc/resources/glass.png
  javadoc/resources/x.png
  javadoc/script-dir/jquery-3.6.0.min.js
  javadoc/script-dir/jquery-ui.min.css
  javadoc/script-dir/jquery-ui.min.js
  javadoc/script.js
  javadoc/search.js
  javadoc/serialized-form.html
  javadoc/stylesheet.css
  javadoc/tag-search-index.js
  javadoc/type-search-index.js
Labels: documentation, ci
